name: 缺陷反馈 (Bug Report)
description: 创建一个报告，帮助我们排查故障并改进 AI 新闻播客生成器
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你抽时间反馈 Bug 问题，这能够帮助整个社区！
  - type: input
    id: environment
    attributes:
      label: 运行操作系统
      description: 请问你是在 macOS, Windows, Linux 下本地运行，还是在使用 GitHub Actions 服务？
      placeholder: 例如：macOS Sonoma 或者 GitHub Actions Ubuntu-latest 环境
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python 版本号
      description: 你目前本地运行的是哪个版本的 Python 呢？(e.g., Python 3.11.0)
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: 描述 Bug 的触发过程或表象
      description: 请清晰且简练地描述遇到了什么错误。
      placeholder: 比如：在拉取某一个特定的 RSS 新闻源格式时无法被 process 步骤处理并报错。
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 相关的控制台报错日志
      description: 请复制并粘贴导致异常的相关终端控制台输出，或者行动日志。
      render: shell
    validations:
      required: false
